import '../../MonacoEditor/monacoSetup'
import { useState, useEffect, useCallback, useRef } from 'react'
import { RotateCcw } from 'lucide-react'
import MonacoEditor, { type BeforeMount, type OnMount } from '@monaco-editor/react'
import type * as Monaco from 'monaco-editor'
import { useTranslation } from 'react-i18next'
import type { ConnectionProvider } from '../../connections.types'
import type { TableColumnMeta } from '../../../../../../preload/index.d'
import { getTypeConfig } from '../../tableTypes'
import TableColumnsEditor, { type TableField, newFieldId } from '../../TableColumnsEditor/TableColumnsEditor'
import './CreateTableDialog.css'
import BaseDialog from '../../../../components/BaseDialog/BaseDialog'
import ErrorBox from '../../../../components/ErrorBox/ErrorBox'
import Button from '../../../../components/Button/Button'

// Re-export TableField for backward compatibility
export type { TableField } from '../../TableColumnsEditor/TableColumnsEditor'

interface CreateTableDialogProps {
  connectionId: string
  databaseName: string
  provider: ConnectionProvider
  editTable?: { schema: string; tableName: string }
  onClose: () => void
  onSuccess: () => void
}

// ── Monaco theme support ───────────────────────────────────────────

const DARK_THEME = 'spiral-dark'
const LIGHT_THEME = 'spiral-light'

const handleBeforeMount: BeforeMount = (monaco) => {
  monaco.editor.defineTheme(DARK_THEME, {
    base: 'vs-dark',
    inherit: true,
    rules: [],
    colors: {
      'editor.background': '#1e1e1e',
      'editorGutter.background': '#141414'
    }
  })
  monaco.editor.defineTheme(LIGHT_THEME, {
    base: 'vs',
    inherit: true,
    rules: [],
    colors: {
      'editor.background': '#ffffff',
      'editorGutter.background': '#e8e8e8'
    }
  })
}

function resolveMonacoTheme(): string {
  if (typeof document !== 'undefined') {
    return document.documentElement.getAttribute('data-theme') === 'light'
      ? LIGHT_THEME
      : DARK_THEME
  }
  return DARK_THEME
}

// ── Helpers ────────────────────────────────────────────────────────

function columnMetaToField(col: TableColumnMeta): TableField {
  let length: number | 'MAX' | null = null
  if (col.maxLength !== null) {
    length = col.maxLength === -1 ? 'MAX' : col.maxLength
  }
  return {
    id: newFieldId(),
    name: col.name,
    type: col.type,
    length,
    precision: col.precision,
    scale: col.scale,
    isNullable: col.isNullable,
    defaultValue: col.defaultValue ?? '',
    isPrimaryKey: col.isPrimaryKey,
    isIdentity: col.isIdentity,
    identitySeed: col.identitySeed ?? 1,
    identityIncrement: col.identityIncrement ?? 1
  }
}

function formatTypeSql(field: TableField, provider: ConnectionProvider): string {
  const cfg = getTypeConfig(provider, field.type)

  // For Postgres, serial types already encode identity; don't add length/precision
  if (provider === 'postgres') {
    const serialTypes = new Set(['smallserial', 'serial', 'bigserial'])
    if (serialTypes.has(field.type.toLowerCase())) return field.type
  }

  let typePart = field.type.toUpperCase()

  if (cfg.hasLength && field.length !== null) {
    const len = field.length === 'MAX' ? 'MAX' : String(field.length)
    typePart += `(${len})`
  } else if (cfg.hasPrecisionScale) {
    const p = field.precision ?? 18
    const s = field.scale ?? 0
    typePart += `(${p}, ${s})`
  }

  return typePart
}

function quoteIdent(name: string, provider: ConnectionProvider): string {
  if (provider === 'postgres' || provider === 'sqlite') return `"${name}"`
  if (provider === 'mysql') return `\`${name}\``
  return `[${name}]`
}

function generateCreateSql(
  schema: string,
  tableName: string,
  fields: TableField[],
  provider: ConnectionProvider,
  databaseName: string
): string {
  if (!tableName.trim() || fields.length === 0) {
    return '-- Add columns and set a table name to generate SQL'
  }

  const schemaId = quoteIdent(schema, provider)
  const tableId = quoteIdent(tableName, provider)
  const pkFields = fields.filter((f) => f.isPrimaryKey)

  if (provider === 'postgres') {
    const colLines: string[] = fields.map((field) => {
      const nameId = quoteIdent(field.name || 'column', provider)
      let typePart = formatTypeSql(field, provider)
      // For Postgres use GENERATED ALWAYS AS IDENTITY for non-serial identity columns
      if (field.isIdentity && !['smallserial', 'serial', 'bigserial'].includes(field.type.toLowerCase())) {
        typePart += ` GENERATED BY DEFAULT AS IDENTITY (START WITH ${field.identitySeed} INCREMENT BY ${field.identityIncrement})`
      }
      const nullPart = field.isNullable ? ' NULL' : ' NOT NULL'
      const defaultPart = field.defaultValue.trim() ? ` DEFAULT ${field.defaultValue.trim()}` : ''
      return `    ${nameId} ${typePart}${nullPart}${defaultPart}`
    })

    if (pkFields.length > 0) {
      const pkCols = pkFields.map((f) => quoteIdent(f.name || 'column', provider)).join(', ')
      colLines.push(`    CONSTRAINT "PK_${tableName}" PRIMARY KEY (${pkCols})`)
    }

    return `CREATE TABLE ${schemaId}.${tableId}\n(\n` + colLines.join(',\n') + '\n)'
  }

  if (provider === 'sqlite') {
    const colLines: string[] = fields.map((field) => {
      const nameId = quoteIdent(field.name || 'column', provider)
      const typePart = formatTypeSql(field, provider)
      const isPk = field.isPrimaryKey && pkFields.length === 1
      const pkPart = isPk ? ' PRIMARY KEY' : ''
      const autoIncPart =
        isPk && field.isIdentity && field.type.toUpperCase() === 'INTEGER' ? ' AUTOINCREMENT' : ''
      const nullPart = field.isNullable ? '' : ' NOT NULL'
      const defaultPart = field.defaultValue.trim() ? ` DEFAULT ${field.defaultValue.trim()}` : ''
      return `    ${nameId} ${typePart}${pkPart}${autoIncPart}${nullPart}${defaultPart}`
    })

    if (pkFields.length > 1) {
      const pkCols = pkFields.map((f) => quoteIdent(f.name || 'column', provider)).join(', ')
      colLines.push(`    PRIMARY KEY (${pkCols})`)
    }

    return `CREATE TABLE ${tableId}\n(\n` + colLines.join(',\n') + '\n)'
  }

  if (provider === 'mysql') {
    const colLines: string[] = fields.map((field) => {
      const nameId = quoteIdent(field.name || 'column', provider)
      const typePart = formatTypeSql(field, provider)
      const autoIncPart = field.isIdentity ? ' AUTO_INCREMENT' : ''
      const nullPart = field.isNullable ? ' NULL' : ' NOT NULL'
      const defaultPart = field.defaultValue.trim() ? ` DEFAULT ${field.defaultValue.trim()}` : ''
      return `    ${nameId} ${typePart}${autoIncPart}${nullPart}${defaultPart}`
    })

    if (pkFields.length > 0) {
      const pkCols = pkFields.map((f) => quoteIdent(f.name || 'column', provider)).join(', ')
      colLines.push(`    PRIMARY KEY (${pkCols})`)
    }

    return `CREATE TABLE ${schemaId}.${tableId}\n(\n` + colLines.join(',\n') + '\n)'
  }

  const prefix = `USE [${databaseName}]\n`

  const colLines: string[] = fields.map((field) => {
    const nameId = quoteIdent(field.name || 'column', provider)
    const typePart = formatTypeSql(field, provider)
    const identityPart = field.isIdentity
      ? ` IDENTITY(${field.identitySeed}, ${field.identityIncrement})`
      : ''
    const nullPart = field.isNullable ? ' NULL' : ' NOT NULL'
    const defaultPart = field.defaultValue.trim() ? ` DEFAULT ${field.defaultValue.trim()}` : ''
    return `    ${nameId} ${typePart}${identityPart}${nullPart}${defaultPart}`
  })

  if (pkFields.length > 0) {
    const pkCols = pkFields.map((f) => `[${f.name || 'column'}]`).join(', ')
    colLines.push(`    CONSTRAINT [PK_${tableName}] PRIMARY KEY CLUSTERED (${pkCols})`)
  }

  return prefix + `CREATE TABLE ${schemaId}.${tableId}\n(\n` + colLines.join(',\n') + '\n)'
}

function generateAlterSql(
  schema: string,
  tableName: string,
  originalFields: TableField[],
  currentFields: TableField[],
  provider: ConnectionProvider,
  databaseName: string
): string {
  if (!tableName.trim()) {
    return '-- Set a table name to generate SQL'
  }

  const q = (n: string): string => quoteIdent(n, provider)
  const tableRef = `${q(schema)}.${q(tableName)}`
  const addStatements: string[] = []
  const dropPkStatements: string[] = []
  const dropColStatements: string[] = []
  const alterStatements: string[] = []
  const addPkStatements: string[] = []

  const origById = new Map(originalFields.map((f) => [f.id, f]))
  const currentIds = new Set(currentFields.map((f) => f.id))

  // Added columns
  for (const cur of currentFields) {
    if (!origById.has(cur.id)) {
      const typePart = formatTypeSql(cur, provider)
      const nullPart = cur.isNullable ? ' NULL' : ' NOT NULL'
      const defaultPart = cur.defaultValue.trim() ? ` DEFAULT ${cur.defaultValue.trim()}` : ''
      let identityPart = ''
      if (cur.isIdentity) {
        if (provider === 'postgres') {
          identityPart = ` GENERATED BY DEFAULT AS IDENTITY (START WITH ${cur.identitySeed} INCREMENT BY ${cur.identityIncrement})`
        } else if (provider === 'mysql') {
          identityPart = ' AUTO_INCREMENT'
        } else if (provider !== 'sqlite') {
          identityPart = ` IDENTITY(${cur.identitySeed}, ${cur.identityIncrement})`
        }
      }
      addStatements.push(
        `ALTER TABLE ${tableRef} ADD ${q(cur.name || 'column')} ${typePart}${identityPart}${nullPart}${defaultPart};`
      )
    }
  }

  // PK change detection
  const origPkNames = originalFields.filter((f) => f.isPrimaryKey).map((f) => f.name)
  const curPkNames = currentFields.filter((f) => f.isPrimaryKey).map((f) => f.name || 'column')
  const pkChanged =
    origPkNames.length !== curPkNames.length ||
    origPkNames.some((n) => !curPkNames.includes(n)) ||
    curPkNames.some((n) => !origPkNames.includes(n))

  if (pkChanged) {
    if (origPkNames.length > 0) {
      if (provider === 'postgres') {
        dropPkStatements.push(
          `ALTER TABLE ${tableRef} DROP CONSTRAINT IF EXISTS "PK_${tableName}";`
        )
      } else if (provider === 'sqlite') {
        dropPkStatements.push(
          `-- SQLite does not support dropping primary key constraints directly.`
        )
      } else if (provider === 'mysql') {
        dropPkStatements.push(`ALTER TABLE ${tableRef} DROP PRIMARY KEY;`)
      } else {
        dropPkStatements.push(
          `DECLARE @pkName sysname`,
          `SELECT @pkName = name FROM sys.key_constraints WHERE type = 'PK' AND parent_object_id = OBJECT_ID('${schema}.${tableName}')`,
          `IF @pkName IS NOT NULL EXEC('ALTER TABLE ${tableRef} DROP CONSTRAINT [' + @pkName + ']')`
        )
      }
    }
    if (curPkNames.length > 0) {
      const pkCols = curPkNames.map((n) => q(n)).join(', ')
      if (provider === 'postgres') {
        addPkStatements.push(
          `ALTER TABLE ${tableRef} ADD CONSTRAINT "PK_${tableName}" PRIMARY KEY (${pkCols});`
        )
      } else if (provider === 'sqlite') {
        addPkStatements.push(
          `-- SQLite does not support adding primary key constraints via ALTER TABLE.`
        )
      } else if (provider === 'mysql') {
        addPkStatements.push(`ALTER TABLE ${tableRef} ADD PRIMARY KEY (${pkCols});`)
      } else {
        addPkStatements.push(
          `ALTER TABLE ${tableRef} ADD CONSTRAINT [PK_${tableName}] PRIMARY KEY CLUSTERED (${pkCols});`
        )
      }
    }
  }

  // Dropped columns
  for (const orig of originalFields) {
    if (!currentIds.has(orig.id)) {
      dropColStatements.push(`ALTER TABLE ${tableRef} DROP COLUMN ${q(orig.name)};`)
    }
  }

  // Modified columns
  for (const cur of currentFields) {
    const orig = origById.get(cur.id)
    if (!orig) continue

    const typeChanged =
      cur.type !== orig.type ||
      cur.length !== orig.length ||
      cur.precision !== orig.precision ||
      cur.scale !== orig.scale
    const nullChanged = cur.isNullable !== orig.isNullable
    const nameChanged = cur.name !== orig.name

    if (nameChanged) {
      if (provider === 'postgres' || provider === 'sqlite' || provider === 'mysql') {
        alterStatements.push(
          `ALTER TABLE ${tableRef} RENAME COLUMN ${q(orig.name)} TO ${q(cur.name)};`
        )
      } else {
        alterStatements.push(
          `EXEC sp_rename '${schema}.${tableName}.${orig.name}', '${cur.name}', 'COLUMN';`
        )
      }
    }

    if (typeChanged || nullChanged) {
      if (cur.isIdentity !== orig.isIdentity) {
        alterStatements.push(
          `-- WARNING: Identity cannot be added/removed from an existing column via ALTER COLUMN.`
        )
        alterStatements.push(
          `-- Column ${q(cur.name)}: manual steps required (recreate the column or the table).`
        )
      } else if (provider === 'postgres') {
        const typePart = formatTypeSql(cur, provider)
        if (typeChanged) {
          alterStatements.push(
            `ALTER TABLE ${tableRef} ALTER COLUMN ${q(cur.name || 'column')} TYPE ${typePart};`
          )
        }
        if (nullChanged) {
          alterStatements.push(
            cur.isNullable
              ? `ALTER TABLE ${tableRef} ALTER COLUMN ${q(cur.name || 'column')} DROP NOT NULL;`
              : `ALTER TABLE ${tableRef} ALTER COLUMN ${q(cur.name || 'column')} SET NOT NULL;`
          )
        }
      } else if (provider === 'sqlite') {
        alterStatements.push(
          `-- SQLite does not support altering column types or nullability via ALTER TABLE.`
        )
      } else if (provider === 'mysql') {
        const typePart = formatTypeSql(cur, provider)
        const nullPart = cur.isNullable ? ' NULL' : ' NOT NULL'
        alterStatements.push(
          `ALTER TABLE ${tableRef} MODIFY COLUMN ${q(cur.name || 'column')} ${typePart}${nullPart};`
        )
      } else {
        const typePart = formatTypeSql(cur, provider)
        const nullPart = cur.isNullable ? ' NULL' : ' NOT NULL'
        alterStatements.push(
          `ALTER TABLE ${tableRef} ALTER COLUMN ${q(cur.name || 'column')} ${typePart}${nullPart};`
        )
      }
    }
  }

  const allStatements = [
    ...addStatements,
    ...dropPkStatements,
    ...dropColStatements,
    ...alterStatements,
    ...addPkStatements
  ]

  if (allStatements.length === 0) {
    return '-- No changes detected'
  }

  if (provider === 'sqlserver') {
    return `USE [${databaseName}]\n` + allStatements.join('\n')
  }

  return allStatements.join('\n')
}

// ── Component ──────────────────────────────────────────────────────

function CreateTableDialog({
  connectionId,
  databaseName,
  provider,
  editTable,
  onClose,
  onSuccess
}: CreateTableDialogProps): React.JSX.Element {
  const { t } = useTranslation()
  const isEditMode = editTable !== undefined

  const [schema, setSchema] = useState(editTable?.schema ?? (provider === 'postgres' ? 'public' : provider === 'mysql' ? databaseName : 'dbo'))
  const [tableName, setTableName] = useState(editTable?.tableName ?? '')
  const [fields, setFields] = useState<TableField[]>([])
  const [originalFields, setOriginalFields] = useState<TableField[]>([])

  const [sqlText, setSqlText] = useState('')
  const sqlEditorRef = useRef<Monaco.editor.IStandaloneCodeEditor | null>(null)
  const lastInternalSqlRef = useRef('')
  const isExternalSqlUpdateRef = useRef(false)
  const [isSqlManuallyEdited, setIsSqlManuallyEdited] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [serverError, setServerError] = useState<string | null>(null)
  const [serverSql, setServerSql] = useState<string | null>(null)
  const [nameError, setNameError] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(isEditMode)
  const [loadError, setLoadError] = useState<string | null>(null)

  // ── Load existing table schema in edit mode ──

  useEffect(() => {
    if (!isEditMode || !editTable) return

    setIsLoading(true)
    window.api.database
      .getTableSchema(connectionId, databaseName, editTable.schema, editTable.tableName)
      .then((result) => {
        if (result.status === 'error') {
          setLoadError(result.message)
          return
        }
        const loaded = result.columns.map(columnMetaToField)
        setFields(loaded)
        setOriginalFields(loaded.map((f) => ({ ...f })))
      })
      .catch((err) => {
        setLoadError(err instanceof Error ? err.message : String(err))
      })
      .finally(() => setIsLoading(false))
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // ── Regenerate SQL whenever inputs change (unless manually edited) ──

  const regenerateSql = useCallback(() => {
    const sql = isEditMode
      ? generateAlterSql(schema, tableName, originalFields, fields, provider, databaseName)
      : generateCreateSql(schema, tableName, fields, provider, databaseName)
    setSqlText(sql)
  }, [isEditMode, schema, tableName, fields, originalFields, provider, databaseName])

  const isSqlManuallyEditedRef = useRef(isSqlManuallyEdited)
  isSqlManuallyEditedRef.current = isSqlManuallyEdited

  useEffect(() => {
    if (!isSqlManuallyEditedRef.current) {
      regenerateSql()
    }
  }, [regenerateSql])

  // ── SQL reset ──

  function handleResetSql(): void {
    setIsSqlManuallyEdited(false)
    regenerateSql()
  }

  // Apply external SQL changes (e.g. auto-regeneration, reset) to the editor imperatively.
  // The isExternalSqlUpdateRef flag prevents onChange from treating this as a manual edit.
  useEffect(() => {
    const editor = sqlEditorRef.current
    if (!editor) return
    if (sqlText === lastInternalSqlRef.current) return
    lastInternalSqlRef.current = sqlText
    isExternalSqlUpdateRef.current = true
    editor.setValue(sqlText)
    isExternalSqlUpdateRef.current = false
  }, [sqlText])

  const handleSqlMount: OnMount = (editor) => {
    sqlEditorRef.current = editor
    // Sync ref with whatever the editor actually rendered as its initial content.
    // This prevents a spurious setValue() call when the editor mounts after
    // regenerateSql() has already updated sqlText.
    lastInternalSqlRef.current = editor.getValue()
  }

  function handleSqlChange(value: string): void {
    if (isExternalSqlUpdateRef.current) return
    lastInternalSqlRef.current = value
    setSqlText(value)
    setIsSqlManuallyEdited(true)
  }

  // ── Validation ──

  function validateForm(): boolean {
    if (!tableName.trim()) {
      setNameError(t('explorer.createTable.validation.nameRequired'))
      return false
    }
    if (/[[\]']/.test(tableName)) {
      setNameError(t('explorer.createTable.validation.nameInvalidChars'))
      return false
    }
    setNameError(null)
    return true
  }

  // ── Submit ──

  async function handleSubmit(): Promise<void> {
    if (!validateForm()) return
    if (!sqlText.trim() || sqlText.startsWith('-- ')) {
      setServerError(t('explorer.createTable.validation.noSql'))
      return
    }
    setServerError(null)
    setServerSql(null)
    setIsSubmitting(true)
    try {
      const result = await window.api.database.executeQuery(connectionId, sqlText, undefined, undefined, provider === 'postgres' ? databaseName : undefined)
      if (result.status === 'error') {
        setServerError(result.message)
        setServerSql(sqlText)
        return
      }
      onSuccess()
    } catch (err) {
      setServerError(err instanceof Error ? err.message : t('explorer.createTable.unknownError'))
      setServerSql(sqlText)
    } finally {
      setIsSubmitting(false)
    }
  }

  // ── Render ──

  const dialogTitle = isEditMode
    ? t('explorer.editTable.dialogTitle', { tableName: editTable!.tableName })
    : t('explorer.createTable.dialogTitle')

  const submitLabel = isEditMode
    ? isSubmitting
      ? t('explorer.editTable.savingButton')
      : t('explorer.editTable.saveButton')
    : isSubmitting
      ? t('explorer.createTable.creatingButton')
      : t('explorer.createTable.createButton')

  const ctdFooter = (
    <>
      <div className="create-table-dialog__footer-error">
        {serverError && <ErrorBox error={serverError} statement={serverSql ?? undefined} />}
      </div>
      <div className="dialog__footer-right">
        <Button
              variant="ghost"
          onClick={onClose}
          disabled={isSubmitting}
        >
          {t('explorer.createTable.cancelButton')}
        </Button>
        <Button
              variant="primary"
          onClick={handleSubmit}
          disabled={isSubmitting || isLoading}
        >
          {submitLabel}
        </Button>
      </div>
    </>
  )

  return (
    <BaseDialog
      title={dialogTitle}
      onClose={onClose}
      width="90vw"
      maxWidth="1100px"
      height="90vh"
      maxHeight="820px"
      minWidth="720px"
      minHeight="580px"
      footerSpaceBetween
      footer={ctdFooter}
    >
        {/* Table name / schema row */}
        <div className="create-table-dialog__name-row">
          <div className="create-table-dialog__name-field create-table-dialog__name-field--schema">
            <label className="create-table-dialog__label" htmlFor="ctd-schema">
              {t('explorer.createTable.schemaLabel')}
            </label>
            <input
              id="ctd-schema"
              className="create-table-dialog__input"
              type="text"
              value={schema}
              onChange={(e) => setSchema(e.target.value)}
              placeholder="dbo"
              disabled={isLoading || isSubmitting}
            />
          </div>
          <div className="create-table-dialog__name-field create-table-dialog__name-field--name">
            <label className="create-table-dialog__label" htmlFor="ctd-tablename">
              {t('explorer.createTable.tableNameLabel')}
            </label>
            <input
              id="ctd-tablename"
              className={`create-table-dialog__input${nameError ? ' create-table-dialog__input--error' : ''}`}
              type="text"
              value={tableName}
              onChange={(e) => {
                setTableName(e.target.value)
                if (nameError) setNameError(null)
              }}
              placeholder={t('explorer.createTable.tableNamePlaceholder')}
              autoFocus={!isEditMode}
              disabled={isLoading || isSubmitting || isEditMode}
            />
            {nameError && <span className="create-table-dialog__name-error">{nameError}</span>}
          </div>
        </div>

        {/* Body */}
        {isLoading ? (
          <div className="create-table-dialog__loading">
            <span className="create-table-dialog__spinner" aria-hidden="true" />
            <span>{t('explorer.createTable.loading')}</span>
          </div>
        ) : loadError ? (
          <div className="create-table-dialog__loading create-table-dialog__loading--error">
            {loadError}
          </div>
        ) : (
          <div className="create-table-dialog__body">
            {/* Top split: columns + properties */}
            <TableColumnsEditor
              fields={fields}
              onFieldsChange={setFields}
              provider={provider}
              disabled={isSubmitting}
            />

            {/* SQL preview section */}
            <div className="create-table-dialog__sql-section">
              <div className="create-table-dialog__sql-header">
                <h3 className="create-table-dialog__sql-title">
                  {t('explorer.createTable.sqlPreviewTitle')}
                </h3>
                {isSqlManuallyEdited && (
                  <button
                    className="create-table-dialog__sql-reset-btn create-table-dialog__sql-reset-btn--active"
                    onClick={handleResetSql}
                    title={t('explorer.createTable.resetSqlTitle')}
                  >
                    <RotateCcw size={11} />
                    {t('explorer.createTable.resetSqlButton')}
                  </button>
                )}
              </div>
              <div className="create-table-dialog__sql-editor">
                <MonacoEditor
                  language="sql"
                  defaultValue={sqlText}
                  onMount={handleSqlMount}
                  theme={resolveMonacoTheme()}
                  beforeMount={handleBeforeMount}
                  onChange={(val) => handleSqlChange(val ?? '')}
                  options={{
                    lineNumbers: 'on',
                    lineNumbersMinChars: 3,
                    minimap: { enabled: false },
                    fontSize: 13,
                    wordWrap: 'on',
                    scrollBeyondLastLine: false,
                    automaticLayout: true,
                    tabSize: 2,
                    renderLineHighlight: 'line',
                    scrollbar: { vertical: 'auto', horizontal: 'auto' },
                    padding: { top: 8, bottom: 8 }
                  }}
                />
              </div>
            </div>
          </div>
        )}

    </BaseDialog>
  )
}

export default CreateTableDialog